---
- hosts: localhost
  # vars_files: secret.yml
  tasks:
  - name: Notify accounts of an update
    mail:
      host: smtp.gmail.com
      port: 587
      # username: allen@shotover.com
      # password: "{{ p }}"
      from: alerts@shotover.com
      to: dns@shotover.com, alerts@shotover.com, allen@shotover.com
      subject: DNS Blacklist Updated
      body: 
        'Hello,
        
        The DNS blacklist has been updated. See attached for details (but not just yet).
        
        Sincerely,
        
        Mr. Roboto'
    delegate_to: localhost