---
- name: Auto-notify users of a DNS blacklist update
  hosts: dns
  tasks:
  - name: Notify accounts of an update
    mail:
      host: smtp.gmail.com
      port: 587
      username: "{{ lookup('env', 'SMTP_USERNAME') }}"
      password: "{{ lookup('env', 'SMTP_PASSWORD') }}"
      from: allen@shotover.com
      # to: dns@shotover.com, alerts@shotover.com, allen@shotover.com
      to: allen@shotover.com
      subject: DNS Blacklist Updated
      body: 
        'Hello,
        
        The DNS blacklist has been updated. See attached for details (but not just yet).
        
        Sincerely,
        
        Mr. Roboto'
